"""add incomplete status and float order_index

Revision ID: 40529fe4cdb1
Revises: 103c74906a01
Create Date: 2026-03-26 23:21:51.326062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40529fe4cdb1'
down_revision: Union[str, Sequence[str], None] = '103c74906a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE interviewstatus ADD VALUE IF NOT EXISTS 'INCOMPLETE'")
    op.alter_column('questions', 'order_index',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'order_index',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # PostgreSQL does not support removing a single enum value safely in-place.
    # ### end Alembic commands ###
